### ISSUE TITLE
build_imgs_package.sh is not executable, but README suggests it should be

### ISSUE THREAD

**Issue by balister** [EttusResearch/ettus-docker#5]
[oe-builder@0d7d4b1af942 ~]$ ./meta-ettus/contrib/build_imgs_package.sh
bash: ./meta-ettus/contrib/build_imgs_package.sh: Permission denied
[oe-builder@0d7d4b1af942 ~]$ ls -l ./meta-ettus/contrib/build_imgs_package.sh
-rw-rw-r--. 1 oe-builder oe-builder 3766 Oct 23 14:03 ./meta-ettus/contrib/build_imgs_package.sh

**Comment by balister** [comment]
Ouch, this lead to building with meta-ettus dirty, leading to:

root@ni-e320-31A816E:~# cat /etc/build 
-----------------------
Build Configuration:  |
-----------------------
DISTRO = Alchemy
DISTRO_VERSION = 2018.04
-----------------------
Layer Revisions:      |
-----------------------
meta              = HEAD:84f19e78d9b1f3d634cf1d46ce48f24670199d0b 
meta-oe           = HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f 
meta-python       = HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f 
meta-filesystems  = HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f 
meta-networking   = HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f 
meta-mender-core  = HEAD:defa27d65e1e49fc19987987df28bfc2cb0accfc 
meta-tpm          = HEAD:2160c5de874234045ba4e201a0703185b65dbae4 
meta-ettus-core   = HEAD:e764e480705d32529eab879074f426544f8972ea -- modified
meta-alchemy      = HEAD:e764e480705d32529eab879074f426544f8972ea -- modified
meta-neon         = HEAD:e764e480705d32529eab879074f426544f8972ea -- modified
meta-mender-neon  = HEAD:e764e480705d32529eab879074f426544f8972ea -- modified

I have zero confidence that what is installed on the device is in revision control now. I know the diff is only the flags on a file, but this looks dreadful to the end user. The shipping image is like this also.

**Comment by mbr0wn** [comment]
Thanks, good catch. I've fixed this in our thud branch, which will be used for our upcoming 3.15 release.
